version: "3"

services:
    client:
        image: nginx
        ports:
            - 127.0.0.1:3001:80
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
